version: '3.1'

services:

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=jg_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
