# Generated by Django 3.1.7 on 2021-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_deliveryoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name_plural': 'Delivery Options'},
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='delivery_sku',
            field=models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
