# Generated by Django 3.1.7 on 2021-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Not Active')], default=False),
        ),
    ]
