# Generated by Django 3.1.7 on 2021-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_deliveryoptions_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('out_for_delivery', 'Out For Delivery'), ('complete', 'Complete'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='processing', max_length=100),
        ),
    ]
