# Generated by Django 3.1.7 on 2021-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('dispatched', 'Dispatched'), ('complete', 'Complete'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='processing', max_length=100),
        ),
    ]
