# Generated by Django 3.1.7 on 2021-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210308_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingimage',
            options={'ordering': ['image_location'], 'verbose_name_plural': 'Landing Images'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name'], 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='landingimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/landing-images'),
        ),
    ]
