# Generated by Django 3.1.7 on 2021-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210308_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Not Active')], default=False),
        ),
    ]
