# Generated by Django 3.1.7 on 2021-06-24 10:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210324_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionalVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/instructional-videos')),
            ],
            options={
                'verbose_name_plural': 'Instructional Video',
                'ordering': ['video'],
            },
        ),
    ]
