# Generated by Django 3.1.7 on 2021-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productimage_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Main Picture'), (2, '2nd Picture'), (3, '3rd Picture'), (4, 'Last Picture')], unique=True),
        ),
    ]
